### ISSUE TITLE
Better readability on issue list.

### ISSUE THREAD

**Issue by nnatsd12349** [swindell4/MO8_Final_Project#14]
The issue list should be more descriptive. I have to open each Mod4 Deadline 1 to see which one each is before choosing the right one to comment on.

Also, assigning people on issues would help differentiate them.

**Comment by swindell4** [comment]
Acknowledged. 

If you go to projects. You can find Final_Project. On this board you can see each persons name alone with their tasks. use the links to the issues under your name to be directed to the issues you are working on. Archive tasks once finished.
